name: CI/CD
on:
  pull_request:
    branches:
    - main
    types:
    - closed

env:
  IMAGE_REGISTRY: docker.io
  DIFF_URL: "${{github.event.pull_request.diff_url}}"
  IS_MERGED: ${{github.event.pull_request.merged == true}}
jobs: 
  ci-cd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get modified images
      run: |
        IMAGES=$(curl -fsL $DIFF_URL \
        | sed -ne 's/^diff --git a\/2igs\///gp' \
        | awk -F'/' '{print $1}' | sed '/^$/d' | uniq)
        NUM_IMAGES=$(printf "%s\n" $IMAGES | sed '/^$/d' | awk 'END{print NR}')
        if [ ${NUM_IMAGES} != "0" ]
        then
          echo -e "Changed images:\n$IMAGES"
          echo "Number of images changed: $NUM_IMAGES"
          if [ ${NUM_IMAGES} == "1" ]
          then 
            IMAGE_NAME=$IMAGES
            echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

            IMAGE_SHA="${GITHUB_SHA:0:10}"
            echo "IMAGE_SHA=${IMAGE_SHA}" >> $GITHUB_ENV 

            BUILD_CONTEXT="2igs/$IMAGE_NAME"
            echo "BUILD_CONTEXT=${BUILD_CONTEXT}" >> $GITHUB_ENV  

            APP_VERSION=$(sed -ne 's/^version: //gp' ${BUILD_CONTEXT}/metadata.yaml )
            echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV    

            IMAGE_TAG=$([ "${IS_MERGED}" == "true" ] && echo "${APP_VERSION}" || echo "${IMAGE_SHA}")
            echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV    

            exit 0
          else
            echo "::error::More than one image was changed!"
            exit 1
          fi
        else
          echo "::error::No image was changed!" >&2
          exit 1
        fi
    - name: Build and push container Image
      run: |
        docker buildx create --use --driver=docker-container
        docker login -u=${{ secrets.DOCKER_CD_USER }} -p=${{ secrets.DOCKER_CD_TOKEN }} docker.io
        docker buildx build --push -t ${IMAGE_REGISTRY}/${{ secrets.DOCKER_CD_USER }}/${IMAGE_NAME}:${IMAGE_TAG} \
        --cache-from type=registry,ref=${IMAGE_REGISTRY}/${{ secrets.DOCKER_CD_USER }}/cache:${IMAGE_NAME} \
        --cache-to type=registry,ref=${IMAGE_REGISTRY}/${{ secrets.DOCKER_CD_USER }}/cache:${IMAGE_NAME} \
        ${BUILD_CONTEXT}
        docker logout